// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL082b66mcROYRTpMfnmq1x0s4sXd5yaQ',
    appId: '1:516429169971:web:d59fb7fa2e79cfe5b16a46',
    messagingSenderId: '516429169971',
    projectId: 'collegecampusapk',
    authDomain: 'collegecampusapk.firebaseapp.com',
    storageBucket: 'collegecampusapk.firebasestorage.app',
    measurementId: 'G-WGT9GZKV4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKs0WNmXLm5QeY86_iL-A4ZRt5eh8wA_Y',
    appId: '1:516429169971:android:822e3dedfc006d3cb16a46',
    messagingSenderId: '516429169971',
    projectId: 'collegecampusapk',
    storageBucket: 'collegecampusapk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXlfd0p4eyeHEPD5QY70gVQODHg_-Vwrw',
    appId: '1:516429169971:ios:5a3e0c34fc866239b16a46',
    messagingSenderId: '516429169971',
    projectId: 'collegecampusapk',
    storageBucket: 'collegecampusapk.firebasestorage.app',
    iosBundleId: 'com.example.collegecampusapk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXlfd0p4eyeHEPD5QY70gVQODHg_-Vwrw',
    appId: '1:516429169971:ios:5a3e0c34fc866239b16a46',
    messagingSenderId: '516429169971',
    projectId: 'collegecampusapk',
    storageBucket: 'collegecampusapk.firebasestorage.app',
    iosBundleId: 'com.example.collegecampusapk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL082b66mcROYRTpMfnmq1x0s4sXd5yaQ',
    appId: '1:516429169971:web:9b4532cf61099d85b16a46',
    messagingSenderId: '516429169971',
    projectId: 'collegecampusapk',
    authDomain: 'collegecampusapk.firebaseapp.com',
    storageBucket: 'collegecampusapk.firebasestorage.app',
    measurementId: 'G-MXKC55MMMB',
  );

}